/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cli.app

import cli.app.parser.processFile
import kotlinx.cli.ArgParser
import kotlinx.cli.ArgType
import kotlinx.cli.default

fun main(args: Array<String>) {
    val parser = ArgParser("${App.appName}:: ${App.version}")
    val batchLinesEnabled by parser.option(ArgType.Boolean, shortName = "v", description = "verbose").default(false)
    val file by parser.option(ArgType.String, shortName = "f", description = "File")

    parser.parse(args);

    if (file != null) {
        processFile(file!!, batchLinesEnabled)
    } else {
        println("A File argument ('-f') is required to run this script")
    }
}

object App {
    const val appName = "ACH CLI App"
    const val version = "0.0.1"
}
