name: Main CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: ./gradlew test jacocoTestReport
      - name: Build
        run: ./gradlew cli-app:packageDistribution
      - name: Create Archive
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release-${{github.run_number}}.zip'
          path: 'dist/'
          type: 'zip'
      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'ach-cli-release-${{github.run_number}}.zip'
          token: ${{ secrets.PUBLISH_TOKEN }}
          tag: Release-${{github.run_number}}
